// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxftwwcsxhmcokbdwmiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4ZnR3d2NzeGhtY29rYmR3bWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTA4NTYsImV4cCI6MjA2NTY2Njg1Nn0.sPOmy6CbjogSase5IrhzmJ5vqWKiqpqMcgyJQbdnB1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);